-- articles
insert into public.articles (id,title,slug,excerpt,content,category,author,image,image_alt,published_at,is_published) values ($q$news-1$q$,$q$HIMA TL UNTAN Tanam 1000 Pohon di Kawasan Mangrove Mempawah$q$,$q$hima-tl-untan-tanam-1000-pohon-2025$q$,$q$Kegiatan penanaman 1000 pohon mangrove berhasil dilaksanakan sebagai bentuk kepedulian terhadap ekosistem pesisir Kalimantan Barat.$q$,$q$<p>Pontianak — Himpunan Mahasiswa Teknik Lingkungan Universitas Tanjungpura (HIMA TL UNTAN) berhasil melaksanakan kegiatan penanaman 1000 pohon mangrove di kawasan pesisir Mempawah, Kalimantan Barat.</p>
<p>Kegiatan yang berlangsung pada Sabtu (15/06/2025) ini diikuti oleh lebih dari 100 mahasiswa Teknik Lingkungan beserta dosen pembimbing. Acara ini merupakan bagian dari program kerja Departemen Dalam Negeri periode 2025/2026.</p>
<p>"Sebagai mahasiswa Teknik Lingkungan, sudah menjadi tanggung jawab kami untuk terlibat langsung dalam upaya pelestarian lingkungan," ujar Ketua Pelaksana.</p>$q$,$q$Kegiatan$q$,$q$Tim Kominfo$q$,$q$/placeholder-news.png$q$,$q$Mahasiswa HIMA TL menanam mangrove$q$,$q$2025-06-16$q$::date,true) on conflict (id) do nothing;
insert into public.articles (id,title,slug,excerpt,content,category,author,image,image_alt,published_at,is_published) values ($q$news-2$q$,$q$Seminar Nasional: Teknologi Pengolahan Air Limbah Berkelanjutan$q$,$q$seminar-nasional-teknologi-air-limbah-2025$q$,$q$HIMA TL UNTAN menyelenggarakan seminar nasional dengan pembicara dari Kementerian LHK dan akademisi terkemuka.$q$,$q$<p>Departemen Pendidikan HIMA TL UNTAN sukses menyelenggarakan Seminar Nasional bertema "Inovasi Teknologi Pengolahan Air Limbah untuk Pembangunan Berkelanjutan".</p>
<p>Acara ini menghadirkan pembicara dari Kementerian Lingkungan Hidup dan Kehutanan serta professor dari ITB dan UI. Lebih dari 300 peserta dari berbagai universitas di Indonesia turut berpartisipasi secara hybrid.</p>$q$,$q$Seminar$q$,$q$Tim Kominfo$q$,$q$/placeholder-news.png$q$,$q$Seminar Nasional HIMA TL UNTAN$q$,$q$2025-05-20$q$::date,true) on conflict (id) do nothing;
insert into public.articles (id,title,slug,excerpt,content,category,author,image,image_alt,published_at,is_published) values ($q$news-3$q$,$q$Pembukaan Pre-Order Hoodie Green Engineering Batch 2$q$,$q$pre-order-hoodie-green-engineering-batch-2$q$,$q$Kabar gembira! Hoodie Green Engineering batch 2 resmi dibuka. Segera pesan sebelum kuota habis.$q$,$q$<p>Departemen Kewirausahaan HIMA TL UNTAN membuka pre-order Hoodie Green Engineering Batch 2. Hoodie ini hadir dengan desain baru yang lebih fresh namun tetap mempertahankan identitas Teknik Lingkungan.</p>
<p>Bahan fleece premium, tersedia dalam ukuran M hingga XXL. Harga Rp195.000 sudah termasuk packaging eksklusif.</p>
<p>Pre-order dibuka hingga 10 Agustus 2026 atau sampai kuota 40 pcs terpenuhi.</p>$q$,$q$Merchandise$q$,$q$Dept. KWU$q$,$q$/placeholder-news.png$q$,$q$Hoodie Green Engineering Batch 2$q$,$q$2025-07-01$q$::date,true) on conflict (id) do nothing;
insert into public.articles (id,title,slug,excerpt,content,category,author,image,image_alt,published_at,is_published) values ($q$news-4$q$,$q$HIMA TL UNTAN Raih Juara 1 Kompetisi Paper Lingkungan Se-Kalimantan$q$,$q$juara-1-kompetisi-paper-lingkungan$q$,$q$Delegasi HIMA TL UNTAN berhasil meraih juara pertama dalam kompetisi paper ilmiah tingkat regional.$q$,$q$<p>Tim delegasi dari HIMA TL UNTAN berhasil membawa pulang trophy juara 1 dalam Kompetisi Paper Ilmiah Lingkungan Se-Kalimantan yang diselenggarakan di Universitas Lambung Mangkurat, Banjarmasin.</p>
<p>Paper berjudul "Optimasi Fitoremediasi Menggunakan Tanaman Lokal untuk Pengolahan Grey Water Permukiman" berhasil meyakinkan dewan juri.</p>$q$,$q$Prestasi$q$,$q$Tim Kominfo$q$,$q$/placeholder-news.png$q$,$q$Tim HIMA TL dengan trophy juara$q$,$q$2025-04-10$q$::date,true) on conflict (id) do nothing;

-- departments
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-bph$q$,$q$Badan Pengurus Harian$q$,$q$bph$q$,$q$Badan Pengurus Harian (BPH) merupakan pengurus inti HIMA TL UNTAN yang terdiri dari Ketua, Sekretaris, dan Bendahara. BPH bertanggung jawab atas koordinasi seluruh kegiatan organisasi dan pengambilan keputusan strategis.$q$,$q$Star$q$,0) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-bph-1$q$,$q$dept-bph$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$bph1$q$,$q$period-bph-1$q$,$q$Ketua HIMA$q$,$q$Ketua$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$bph2$q$,$q$period-bph-1$q$,$q$Sekretaris HIMA$q$,$q$Sekretaris$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$bph3$q$,$q$period-bph-1$q$,$q$Bendahara HIMA$q$,$q$Bendahara$q$,$q$/placeholder-avatar.png$q$,null,3) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-1$q$,$q$Dalam Negeri$q$,$q$dagri$q$,$q$Departemen Dalam Negeri bertanggung jawab dalam mengelola hubungan internal organisasi, membangun solidaritas antar anggota, serta menyelenggarakan kegiatan yang mempererat kebersamaan mahasiswa Teknik Lingkungan UNTAN.$q$,$q$Home$q$,1) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-1$q$,$q$dept-1$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m1$q$,$q$period-1$q$,$q$Ahmad Rizki$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m2$q$,$q$period-1$q$,$q$Siti Nurhaliza$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m3$q$,$q$period-1$q$,$q$Budi Santoso$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,3) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m4$q$,$q$period-1$q$,$q$Dewi Lestari$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,4) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-2$q$,$q$dept-1$q$,$q$2024/2025$q$,false,$q$2024-01-01$q$::date,$q$2024-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m5$q$,$q$period-2$q$,$q$Rudi Hartono$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m6$q$,$q$period-2$q$,$q$Ani Wijaya$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-2$q$,$q$Luar Negeri$q$,$q$lugri$q$,$q$Departemen Luar Negeri bertugas menjalin dan memperkuat hubungan eksternal HIMA TL UNTAN dengan organisasi mahasiswa lain, instansi pemerintah, serta pihak-pihak terkait di luar kampus.$q$,$q$Globe$q$,2) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-3$q$,$q$dept-2$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m7$q$,$q$period-3$q$,$q$Fajar Nugraha$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m8$q$,$q$period-3$q$,$q$Maya Putri$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m9$q$,$q$period-3$q$,$q$Rizal Firmansyah$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,3) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-3$q$,$q$Kewirausahaan$q$,$q$kwu$q$,$q$Departemen Kewirausahaan mengelola kegiatan wirausaha HIMA TL UNTAN, termasuk merchandise resmi, bazar, dan program pengembangan jiwa kewirausahaan mahasiswa.$q$,$q$Briefcase$q$,3) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-4$q$,$q$dept-3$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m10$q$,$q$period-4$q$,$q$Dian Permata$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m11$q$,$q$period-4$q$,$q$Eko Prasetyo$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m12$q$,$q$period-4$q$,$q$Fitri Handayani$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,3) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m13$q$,$q$period-4$q$,$q$Gilang Ramadhan$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,4) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-4$q$,$q$Pendidikan$q$,$q$depdik$q$,$q$Departemen Pendidikan fokus pada peningkatan kualitas akademik mahasiswa melalui tutorial, seminar, workshop, dan kegiatan ilmiah lainnya.$q$,$q$GraduationCap$q$,4) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-5$q$,$q$dept-4$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m14$q$,$q$period-5$q$,$q$Hana Safira$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m15$q$,$q$period-5$q$,$q$Irfan Maulana$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-5$q$,$q$Rumah Tangga$q$,$q$rumah-tangga$q$,$q$Departemen Rumah Tangga bertanggung jawab atas logistik, inventaris, dan kebutuhan operasional organisasi sehari-hari.$q$,$q$Wrench$q$,5) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-6$q$,$q$dept-5$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m16$q$,$q$period-6$q$,$q$Joko Widodo$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m17$q$,$q$period-6$q$,$q$Kartika Sari$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.departments (id,name,slug,description,icon,order_index) values ($q$dept-6$q$,$q$Kominfo$q$,$q$kominfo$q$,$q$Departemen Komunikasi dan Informasi mengelola media sosial, website, dokumentasi kegiatan, dan seluruh publikasi informasi HIMA TL UNTAN kepada publik.$q$,$q$Megaphone$q$,6) on conflict (id) do nothing;
insert into public.department_periods (id,department_id,period_label,is_active,start_date,end_date) values ($q$period-7$q$,$q$dept-6$q$,$q$2025/2026$q$,true,$q$2025-01-01$q$::date,$q$2025-12-31$q$::date) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m18$q$,$q$period-7$q$,$q$Lina Marlina$q$,$q$Ketua Departemen$q$,$q$/placeholder-avatar.png$q$,null,1) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m19$q$,$q$period-7$q$,$q$Muhammad Aldi$q$,$q$Wakil Ketua$q$,$q$/placeholder-avatar.png$q$,null,2) on conflict (id) do nothing;
insert into public.department_members (id,period_id,name,position,photo,contact,order_index) values ($q$m20$q$,$q$period-7$q$,$q$Nadia Putri$q$,$q$Staff$q$,$q$/placeholder-avatar.png$q$,null,3) on conflict (id) do nothing;

-- partners
insert into public.partners (id,name,logo,description,website,type,order_index) values ($q$p1$q$,$q$Dinas Lingkungan Hidup Kota Pontianak$q$,null,$q$Mitra kerja sama dalam kegiatan pengelolaan lingkungan dan edukasi masyarakat.$q$,$q$https://pontianakkota.go.id$q$,$q$mitra$q$,0) on conflict (id) do nothing;
insert into public.partners (id,name,logo,description,website,type,order_index) values ($q$p2$q$,$q$PT Aqua Golden Mississippi$q$,null,$q$Sponsor utama kegiatan seminar dan workshop pengelolaan sumber daya air.$q$,null,$q$sponsor$q$,1) on conflict (id) do nothing;
insert into public.partners (id,name,logo,description,website,type,order_index) values ($q$p3$q$,$q$Wahana Lingkungan Hidup Indonesia (WALHI) Kalbar$q$,null,$q$Mitra strategis dalam advokasi dan kampanye pelestarian lingkungan di Kalimantan Barat.$q$,$q$https://walhi.or.id$q$,$q$mitra$q$,2) on conflict (id) do nothing;
insert into public.partners (id,name,logo,description,website,type,order_index) values ($q$p4$q$,$q$Bank Sampah Kalbar Bersih$q$,null,$q$Kolaborasi program pengelolaan sampah dan ekonomi sirkular di lingkungan kampus.$q$,null,$q$mitra$q$,3) on conflict (id) do nothing;

-- ads
insert into public.ads (id,name,blurb,logo,website,active,order_index) values ($q$ad-1$q$,$q$Bank Sampah Kalbar Bersih$q$,$q$Setor sampah terpilah, dapat saldo. Titik jemput tersedia di area kampus UNTAN.$q$,null,$q$https://example.com/bank-sampah-kalbar$q$,true,1) on conflict (id) do nothing;
insert into public.ads (id,name,blurb,logo,website,active,order_index) values ($q$ad-2$q$,$q$Tirta Khatulistiwa$q$,$q$Penyedia instalasi pengolahan air bersih untuk rumah tangga dan industri di Kalimantan Barat.$q$,null,$q$https://example.com/tirta-khatulistiwa$q$,true,2) on conflict (id) do nothing;
insert into public.ads (id,name,blurb,logo,website,active,order_index) values ($q$ad-3$q$,$q$Kopi Kapuas Roastery$q$,$q$Diskon 15% untuk mahasiswa Teknik Lingkungan dengan menunjukkan KTM.$q$,null,$q$https://example.com/kopi-kapuas$q$,true,3) on conflict (id) do nothing;
insert into public.ads (id,name,blurb,logo,website,active,order_index) values ($q$ad-4$q$,$q$EcoPrint Pontianak$q$,$q$Cetak poster, banner, dan merchandise organisasi dengan tinta berbasis air.$q$,null,$q$https://example.com/ecoprint-pontianak$q$,true,4) on conflict (id) do nothing;